chapter:
  url: https://www.chicagodsa.org/
  facebook: https://www.facebook.com/ChicagoDemSocialists/
  instagram: https://www.instagram.com/chicagodsa/
  twitter: https://twitter.com/ChicagoCityDSA
  # Override DSA national logos
  header-logo-svg: "images/CDSA-logo-color.svg"
  header-logo-png-fallback: "images/CDSA-logo-color.png" # 360px square recommended
  background-logo-svg: "images/CDSA-logo-reverse.svg"
  background-logo-png-fallback: "images/CDSA-logo-reverse.png" # 1440px square recommended
google_analytics: # Tracking ID
teamup: # Calendar API key
permalink: pretty
remote_theme: ChicagoDSA/haymarket@v2.2.2

# Set default front matter for Markdown files
defaults:
  -
    scope:
      path: "" # All files
    values:
      lang: en
      layout: default
      image: assets/images/og-image.png

  # Set URLs and language code for collections
  # English   
  -
    scope:
      path: _homepage/en/index.md
    values:
      permalink: / # Set as index
  # Spanish
  -
    scope:
      path: _homepage/es/index.md
    values:
      permalink: /es/
      lang: es

# Manage lists of content with collections
# https://jekyllrb.com/docs/collections/
collections:
  # Homepage translations
  homepage:
    output: true
  # Add single pages in the _pages folder
  pages:
    output: true
