title: Robert's Rules
description: A quick overview of Robert's Rules of Order.
chapter:
  name: Chicago DSA
  url: https://www.chicagodsa.org/
  facebook: https://www.facebook.com/ChicagoDemSocialists/
  instagram: https://www.instagram.com/chicagodsa/
  twitter: https://twitter.com/ChicagoCityDSA
custom-join: # Add custom join URL here
google_analytics: # Tracking ID
teamup: # Calendar API key
permalink: pretty
remote_theme: ChicagoDSA/haymarket@v1.4.9

# Leave empty to disable
banner:
  text:
  link:

defaults:
  -
    scope:
      path: "" # All files
    values:
      layout: default
      image: "assets/images/og-image.png"

# Add collections here
# https://jekyllrb.com/docs/collections/
collections:
  