title: Robert's Rules
description: An overview of Robert's Rules of Order for new DSA members.
chapter:
  name: Chicago DSA
  location: Chicago
  url: https://www.chicagodsa.org/
google_analytics:
remote_theme: ChicagoDSA/haymarket@v1.0.7
