title: Robert's Rules
description: Learn how to participate in DSA meetings.
chapter:
  name: Chicago DSA
  location: Chicago
  url: https://www.chicagodsa.org/
  facebook: https://www.facebook.com/ChicagoDemSocialists/
  instagram: https://www.instagram.com/chicagodsa/
  twitter: https://twitter.com/ChicagoCityDSA
google_analytics:
permalink: pretty
remote_theme: ChicagoDSA/haymarket@v1.2.4

# Leave empty to disable
banner:
  text:
  link:

defaults:
  -
    scope:
      path: "" # All files
    values:
      layout: default
      image: "assets/images/og-image.png"

# Add collections here
# https://jekyllrb.com/docs/collections/
collections: