title: Robert's Rules
description: Learn how to participate in DSA meetings.
chapter:
  name: Chicago DSA
  location: Chicago
  url: https://www.chicagodsa.org/
google_analytics:
remote_theme: ChicagoDSA/haymarket@v1.0.7
